sudo: required

# not necessary, but less confusing if defined
language: python

services:
  - docker

# we do everything in docker for non MacOS, MacOS setup is in .travis/build.sh
install: skip
before_install: skip

stages:
- verify
- test
- name: deploy latest docs
  if: (branch = master OR branch =~ ^infra/$) AND type = push
- name: deploy
  if: tag is PRESENT

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  sudo sed -i '1i 127.0.0.1 test.box' /etc/hosts;
  sudo hostname test.box;
  source ./.travis/lib-util.sh;
  util::docker-run $DISTRO ./.travis/build.sh;
  fi
- if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then ./.travis/build.sh; fi

jobs:
  include:
  - &docker_verify
    stage: verify
    env: DISTRO=fedora:latest PYTHON="2"
    script:
    - source ./.travis/lib-util.sh
    - util::docker-run $DISTRO ./.travis/verify.sh

  - <<: *docker_verify
    env: DISTRO=fedora:latest PYTHON="3"


  # need to explictly define each builder for test due to different os types
  - stage: test
    env: DISTRO=debian:stable PYTHON="2"

  - stage: test
    env: DISTRO=debian:stable PYTHON="3" # 3.4, not 3.5

  - stage: test
    env: DISTRO=debian:stable PYTHON="3" KRB5_VER="heimdal"

  - stage: test
    env: DISTRO=centos:7 PYTHON="2" # el7 doesn't do python3 modules

  - stage: test
    env: DISTRO=fedora:latest PYTHON="3"

  - stage: test
    env: DISTRO=fedora:latest PYTHON="2"

  - &osx_test
    stage: test
    env: PYTHON="2" KRB5_VER="heimdal" PYENV="2.7.14"
    os: osx
    osx_image: xcode9.2
    language: generic # causes issues with pyenv installer when set to python

  - <<: *osx_test
    env: PYTHON="3" KRB5_VER="heimdal" PYENV="3.6.3"

  - &win_test
    stage: test
    env: PYTHON="2" PYENV="2.7.16" EXTRA_BUILDEXT="--compiler=mingw32"
    os: windows
    language: sh  # Windows not supported yet

  - <<: *win_test
    env: PYTHON="3" PYENV="3.6.8"

  - <<: *win_test
    env: PYTHON="3" PYENV="3.7.3"


  - stage: deploy latest docs
    script: skip
    env:
    - DISTRO=fedora:latest
    - PYTHON="3"
    - secure: L5SpEj5+no20PWwC9Y/XNhAfmUvYiuykwSMa/YyqvUuBjdizzpZcHr7Ego5nMdM1TniTxj4pSTM+GbM0FHCzNmAINSRh9g/D3hheRqlRBacqR0XwC9ZZRvkKvtzwnLh4vYWiauq4AoDeR5U6tkEcay6LjE57iMQcLjcKYBc+Eos=
    before_deploy:
    - source ./.travis/lib-util.sh
    - util::docker-run $DISTRO ./.travis/before-docs-deploy.sh

    deploy:
    - provider: script
      script: .travis/docs-deploy.sh travis_docs_build/html latest pythongssapi/python-gssapi
      skip_cleanup: true
      on:
        all_branches: true


  - stage: deploy
    script: skip
    env:
    - DISTRO=fedora:latest
    - PYTHON="3"
    - secure: L5SpEj5+no20PWwC9Y/XNhAfmUvYiuykwSMa/YyqvUuBjdizzpZcHr7Ego5nMdM1TniTxj4pSTM+GbM0FHCzNmAINSRh9g/D3hheRqlRBacqR0XwC9ZZRvkKvtzwnLh4vYWiauq4AoDeR5U6tkEcay6LjE57iMQcLjcKYBc+Eos=
    before_deploy:
    - source ./.travis/lib-util.sh
    - util::docker-run $DISTRO ./.travis/before-deploy.sh
    - ls -alR `pwd`

    deploy:
    - provider: releases
      api_key:
        secure: fAaSSSjd/nUrIpINBjAT590pGF2nGq3I8ee6aGq6IAFpXoa/9eeN5eyOrE4MYucWCwYcH28c7510n35vuZQQor+UZIDo6l0K5M64/NZE1cZ43zOMjw3yHlrsJG+ohPS7YvjqD8GaFlLhF6ZvWvrPmWeijvs8qAT1eL7QoEG0xBk=
      file_glob: true
      file:
        - tag_build/*
      skip_cleanup: true
      on:
        all_branches: true

    - provider: pypi
      user: rharwood
      password:
        secure: "hN861mjtLeC8IysypC6Pqzlazq29I+c69XGjbUR53izYQ90cz2F+B2azVTl9Su9NbXzdsGnhWZrjY1jtYMPIZE15xDaC8vs61QijFClqmyuKNRVzCt1w/sj21hyLXnYIrkAo4e3bswPF+hRGNwfb+rVrR/dqUwd1wyjZBBYMcQE="
      skip_cleanup: true
      docs_dir: travis_docs_build/html
      on:
        all_branches: true
      # NB(directxman12): this is a hack.  Check ./.travis/before-deploy.sh for an explanation.
      distributions: "check"

    - provider: script
      script: .travis/docs-deploy.sh travis_docs_build/html stable pythongssapi/python-gssapi
      skip_cleanup: true
      on:
        all_branches: true

  - &win_deploy
    stage: deploy
    os: windows
    script: # This is egregious hacks around Travis
      - ./.travis/before-deploy-windows-wheels.sh
      - ./.travis/deploy-win.sh
    env:
      - PYTHON="2"
      - PYENV="2.7.16"
      - EXTRA_BUILDEXT="--compiler=mingw32"
    language: sh # Travis doesn't support python here

  - <<: *win_deploy
    env:
      - PYTHON="3"
      - PYENV="3.6.8"

  - <<: *win_deploy
    env:
      - PYTHON="3"
      - PYENV="3.7.3"
